### ISSUE TITLE
Back of Instrument Panel Images

### ISSUE THREAD

**Issue by acirinelli** [allanglen/c172-flight-sim-panel#2]
Thanks for putting this together! I'm using your 3D printed bezels. I was wondering if you have any images of the backside of the panel (encoder wiring) prior to installing over monitor?

**Comment by mccluress** [comment]
I agree!  It looks great but I am unsure if you made all the cuts/routing from the back to be able to mount them and still have the area to screw them in.  I really want to use your designs for this...maybe add a manifold pressure gauge so I can go between a couple of aircraft.  It wouldn't be "accurate" for other aircraft but Id have all the gauges plus some that I need.

**Comment by acirinelli** [comment]
You can always tweak the design and just print another bezel for the extra gauge. I made some adjustments to my layout a s plan to do a different throttle set up so i can fly twins as well.

**Comment by mccluress** [comment]
Hey,
      I'm sure this is a silly question but I was hoping you could help me out.  With ardsimx, what are you using for the encoders on the Directional Gyro?  The left one should turn the card to align it with the compass and the right should be a heading bug.  I see only one encoder spot for directional gyro in ardsimx.  Thanks for any help you can offer.  Looking to get this thing off the ground when I get back home from deployment.

    On ‎Sunday‎, ‎June‎ ‎10‎, ‎2018‎ ‎01‎:‎24‎:‎20‎ ‎AM, Anthony Cirinelli <notifications@github.com> wrote:  
 
 
Reopened #2.

**Comment by acirinelli** [comment]
@mccluress I haven't gotten that far yet, but I would guess you just add another heading sync and then modify the data.cfg file to point to rhe_DG_SYN. Will have to dive in a bit more to figure out if that's correct and up/down, but it shouldn't be too difficult.

**Comment by allanglen** [comment]
@acirinelli I'll get some photos posted of the back of the panel that shows the wiring. I used a dremel router bit to route channels for the wires. Everything fits within the depth of the plywood (plus the depth of the thin tabs for the bezels which match the depth of the metal bezel around the display). This allows the bezels to fit flush against the surface of the display.

I've been meaning to get those details posted but it requires some disassembly. Thanks for prompting me. I'll try to get something posted this weekend.

**Comment by allanglen** [comment]
@mccluress ArdSimX provides pre-configured parameters for convenience but you can connect to any X-Plane dataref. I haven't posted my config file as I was hoping to upgrade to ArdSimX 2 (aka SimVimCockpit) before doing that.

I'm actively using my panel now and busy with my real world flight training so I probably won't upgrade to SimVimCockpit any time soon. I'll go ahead and get my ArdSimX config file posted so you can see how everything connects.

**Comment by mccluress** [comment]
Thanks!  I appreciate it!  I am going to be building a similar instrument panel and your transponder soon.  My com/nav2, DME, and ADF are all LCDs but you did such a great job on that transponder, I'm just gonna steal yours!  Awesome work!  I just cant figure out how you get the XPDR to say "ON" or whatever else besides the transponder code so I cant wait to see your files!  Good luck with your real world training!  Flying is a blast!  Ill probably get into my commercial when I get back home!

    On ‎Friday‎, ‎June‎ ‎15‎, ‎2018‎ ‎02‎:‎34‎:‎44‎ ‎PM, Allan Glen <notifications@github.com> wrote:  
 
 
@mccluress ArdSimX provides pre-configured parameters for convenience but you can connect to any X-Plane dataref. I haven't posted my config file as I was hoping to upgrade to ArdSimX 2 (aka SimVimCockpit) before doing that.

I'm actively using my panel now and busy with my real world flight training so I probably won't upgrade to SimVimCockpit any time soon. I'll go ahead and get my ArdSimX config file posted so you can see how everything connects.

**Comment by acirinelli** [comment]
Awesome 👏 
those look super helpful, thank you!

**Comment by acirinelli** [comment]
My gauge panel work in progress from today. I’m using a 21.5”, so my layout is a little different.
![ba982669-4cab-4549-be2a-83bf8bcc5ee1](https://user-images.githubusercontent.com/3673934/41503631-83c3634e-718d-11e8-9135-b37a71ba04b9.jpeg)

**Comment by acirinelli** [comment]
@allanglen Would you be willing to add your data config file for reference? I cannot figure out how to adjust the TAS indicator with the encoder

**Comment by the1andonlyalt** [comment]
Hi Allen.  Fanstastic work BTW.  This may seem like a silly request.  Any photos of the back of the GNS430?  Like to see your wiring schematic.  I'm planning on building a dumbed down version of yours.  Rough scale and may add the external display till later.  My first goal is to get off the mouse during flying approaches while I work on my Instrument rating.  I expect I may just punch in some buttons and a couple of encoders. hooked to an arduino.   Like to see more of the background build specifics on yours. 

Alt

**Comment by the1andonlyalt** [comment]
And Allan not en.  sorry... i blame either spellcheck or problem lies between keyboard and chair.

**Comment by allanglen** [comment]
There are rear photos here: https://cessna172sim.allanglen.com/docs/avionics/garmin-gns-430/

The buttons and encoders wire to an Arduino. I don't have a schematic of that layout but you can learn more on the ArdSimX site (http://simvim.com/archive/asx_wire.html)
